In [61]:
from google.colab import files
uploaded = files.upload()

Saving cat1.jpg to cat1 (2).jpg
Saving cat2.jpg to cat2 (2).jpg
Saving cat3.jpg to cat3 (2).jpg
Saving color_template.png to color_template (1).png
Saving dog1.jpg to dog1 (2).jpg


In [ ]:
# Adding necessary libaries

import numpy as np                                 # Here the np is the short name to call function numpy
from scipy import misc                             # This libary gives the functionality of reading, writting and manipulating the images.
import matplotlib.pyplot as plt                    # This libary is basically used for ploting.
import cv2                                         # is used for many tasks like image processing,Object detection.


# Here The program reads the images first and then demonstrates them by using Subplot function (plt).

image1 = plt.imread("cat1.jpg")                     # Here we just read the images by plt.imread function.
image2 = plt.imread("cat2.jpg")
image3 = plt.imread("cat3.jpg")
image4 = plt.imread("dog1.jpg")

# Here we are creating figure
Myfigure = plt.figure(figsize=(20,20))             # it creates a figure with a size of 20x20 inches. And figure function is used for creating figures(Sekil)

# Here We are setting values to rows and column variables. it demonstrates that we arrange our  subplots in a single row with four columns.
rows = 1
columns = 4

# Here we are adding subplots at their positions and we show them.
# This code adds a subplot to the figure Myfigure at the specified position, and then it displays image1 in that subplot with a title "cat1".

Myfigure.add_subplot(rows,columns,1)
plt.imshow(image1)
plt.title("cat1")

# This code adds a subplot to the figure Myfigure at the specified position, and then it displays image1 in that subplot with a title "cat2".

Myfigure.add_subplot(rows,columns,2)
plt.imshow(image2)
plt.title("cat2")

# This code adds a subplot to the figure Myfigure at the specified position, and then it displays image1 in that subplot with a title "cat2".

Myfigure.add_subplot(rows,columns,3)
plt.imshow(image3)
plt.title("cat3")

# This code adds a subplot to the figure Myfigure at the specified position, and then it displays image1 in that subplot with a title "dog1".

Myfigure.add_subplot(rows,columns,4)
plt.imshow(image4)
plt.title("dog1")

# The shape of image1 will be printed as a tuple containing three elements: (height, width, channels)

print(image1.shape)








In [ ]:
# Here the  code resizes the images image1, image2, image3, and image4 to a new size of (224, 224) pixels using the cv2.resize()

image1_resized = cv2.resize(image1, (224,224))
image2_resized = cv2.resize(image2, (224, 224))
image3_resized = cv2.resize(image3, (224, 224))
image4_resized = cv2.resize(image4, (224, 224))

# Creating figure
Myfigure = plt.figure(figsize=(20,20))

# Here we are setting values to rows and columns variables
rows = 1
columns = 4

# Here we are adding subplots at their positions and then we demonstrate them.

Myfigure.add_subplot(rows,columns, 1)
plt.imshow(image1_resized)
plt.title("224X224x3_resized_cat1")

Myfigure.add_subplot(rows,columns, 2)
plt.imshow(image2_resized)
plt.title("224X224x3_resized_cat2")

Myfigure.add_subplot(rows,columns, 3)
plt.imshow(image3_resized)
plt.title("224X224x3_resized_cat3")

Myfigure.add_subplot(rows,columns, 4)
plt.imshow(image4_resized)
plt.title("224X224x3_resized_dog1")
plt.show()



In [91]:
# (224, 224, 3)

print(image1_resized.shape)

(224, 224, 3)


In [ ]:
# Example of accessing a pixel value of a color image.
# With following code we are accessing to a pixel value of a color image.

image1 = cv2.imread("cat1.jpg")
image1_RGB = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)
plt.imshow(image1_RGB)
plt.show()

In [93]:
R = image1_RGB[300, 250, 0]
G = image1_RGB[300, 250, 1]
B = image1_RGB[300, 250, 2]
RGB = image1_RGB[300, 250, :]

print('R', R, 'G', G, 'B', B)
print(RGB)

R 29 G 18 B 12
[29 18 12]


In [ ]:
# Task1
# Here we read an image named "color_template.png" by using the cv2.imread()
# And then we Convert the color space of the image from BGR (Blue-Green-Red) to RGB (Red-Green-Blue)

img = cv2.imread("color_template.png")
My_First_RGB_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(My_First_RGB_img)
plt.title("RGB_Color_template")
plt.show()


In [95]:
print(img.shape)

(420, 560, 3)


In [ ]:
# Here we are resizing the picture of color_template to a new size of (224, 224) pixels

RGB_resized_img = cv2.resize(My_First_RGB_img, (224, 224))
plt.imshow(RGB_resized_img)
plt.show()

In [97]:
print(RGB_resized_img.shape)

(224, 224, 3)


In [98]:
# SOLVING THE PROBLEM OF UINT8 DATATYPE
# Which is the default datatype of cv2.imread function
# First we create a numpy 3d array (224,224,3)
# Then We assign every pixels color channel values to this new created array
# it will now store values exactly equal as we pass them into it(Negaive ones for example) it wont rearrange values into[0,255] range
# And in the end we get the original image back

# This code creates a NumPy array image_RGB_NParr initialized with zeros,
# with a shape of (224, 224, 3). This shape indicates an image with a height and width of 224 pixels and 3 color channels (Red, Green, and Blue).

image_RGB_NParr = np.zeros((224,224,3))

for i in range(0, 224):
  for j in range(0, 224):
    image_RGB_NParr[i,j,:] = RGB_resized_img[i,j,:]

In [99]:
# plt.imshow() function allows float the float values only in range [0,1]. So, divide values with 255 so as print the image.

for i in range (0,224):
   for j in range(0,224):
    R = image_RGB_NParr[i,j,0] / 255
    G = image_RGB_NParr[i,j,1] / 255
    B = image_RGB_NParr[i,j,2] / 255
    image_RGB_NParr[i,j,:] = [R,G,B]

In [ ]:
# Here we  Successfully printed the image with float values between[0,1] after dividing them to 255.
plt.imshow(image_RGB_NParr)
plt.show()

In [101]:
# Here we have created Transformatin Matrices
# From RGB to YUV
rgb2yuv_matrix = np.ones((3,3), dtype= np.float32)
rgb2yuv_matrix = [[0.2126, 0.7152, 0.0722], [-0.09991, -0.33609, 0.436], [0.615, -0.55861, -0.05639]]

rgb2yuv_matrix = np.float32(rgb2yuv_matrix)
print(rgb2yuv_matrix)


[[ 0.2126   0.7152   0.0722 ]
 [-0.09991 -0.33609  0.436  ]
 [ 0.615   -0.55861 -0.05639]]


In [102]:
# from YUV to RGB
yuv2rgb_matrix = np.ones((3,3), dtype= np.float32)
yuv2rgb_matrix = [[1, 0, 1.28033], [1, -0.21482, -0.38059], [1, 2.12798, 0]]

yuv2rgb_matrix = np.float32(yuv2rgb_matrix)
print(yuv2rgb_matrix)


[[ 1.       0.       1.28033]
 [ 1.      -0.21482 -0.38059]
 [ 1.       2.12798  0.     ]]


In [103]:
# Multiplying values back with 255

for i in range(0,224):
  for j in range(0,224):
    image_RGB_NParr[i,j,0] = image_RGB_NParr[i,j,0] * 255
    image_RGB_NParr[i,j,1] = image_RGB_NParr[i,j,1] * 255
    image_RGB_NParr[i,j,2] = image_RGB_NParr[i,j,2] * 255

In [104]:
# Creating a 3d numpy arry in order to hold YUV values of image. Then we transform values using transformation matrix that we created earlier.

# Create a numpy array to hold YUV formatted values.

image_YUV_NParr = np.zeros((224,224,3))

for i in range(0,224):
  for j in range(0,224):
    image_YUV_NParr[i,j,:] = np.dot(rgb2yuv_matrix , image_RGB_NParr[i,j,:])


In [105]:
# Dividing values with 255 in order to print image with imshow() function. Get RGB2YUV
for i in range(0,224):
  for j in range(0,224):
    R = image_YUV_NParr[i,j,0] / 255
    G = image_YUV_NParr[i,j,1] / 255
    B = image_YUV_NParr[i,j,2] / 255
    image_YUV_NParr[i,j,:] = [R,G,B]


In [ ]:
plt.title("RGB_to_YUV_image")
plt.imshow(image_YUV_NParr)
plt.show()

In [107]:
# So as to get original YUV values back we multiply each value stored in the matrix with 255.

for i in range(0,224):
  for j in range(0,224):
    image_YUV_NParr[i,j,0] = image_YUV_NParr[i,j,0] * 255
    image_YUV_NParr[i,j,1] = image_YUV_NParr[i,j,1] * 255
    image_YUV_NParr[i,j,2] = image_YUV_NParr[i,j,2] * 255

In [76]:
# Here i created a 3D numpy array, that will be holding R,G and B values to get with using transformation matrix on YUV values.Returns the original image.

In [108]:
image_back2RGB_NParr = np.zeros((224,224,3))

for i in range(0,224):
  for j in range(0,224):
    image_back2RGB_NParr[i,j,:] = np.dot(rgb2yuv_matrix, image_YUV_NParr[i,j,:])

In [109]:
for i in range(0,224):
  for j in range(0,224):
    R = image_back2RGB_NParr[i,j,0] / 255
    G = image_back2RGB_NParr[i,j,1] / 255
    B = image_back2RGB_NParr[i,j,2] / 255
    image_back2RGB_NParr[i,j,:] = [R,G,B]


In [ ]:
# The image will appear in Red,Green and Blue colors.

plt.title("YUV_to_RGB_image")
plt.imshow(image_back2RGB_NParr)
plt.show()

In [112]:
# Task2

# Here i fliped the cat's and dogs's images vertically (Dikey Olarak)

resized_image1_vertically = cv2.flip(image1_resized, 0)
resized_image2_vertically= cv2.flip(image2_resized, 0)
resized_image3_vertically = cv2.flip(image3_resized, 0)
resized_image4_vertically = cv2.flip(image4_resized, 0)


In [113]:
# Here i flipped cat's and dog's images horizontally (yatay olarak)

resized_image1_horizontally = cv2.flip(image1_resized, 1)
resized_image2_horizontally = cv2.flip(image2_resized, 1)
resized_image3_horizontally = cv2.flip(image3_resized, 1)
resized_image4_horizontally = cv2.flip(image4_resized, 1)

In [114]:
# Here i rotated the cat's and dog's images to left by 90 degree.
resized_image1_rotated_90degreeleft = cv2.rotate(image1_resized, cv2.ROTATE_90_COUNTERCLOCKWISE)
resized_image2_rotated_90degreeleft = cv2.rotate(image2_resized, cv2.ROTATE_90_COUNTERCLOCKWISE)
resized_image3_rotated_90degreeleft = cv2.rotate(image3_resized, cv2.ROTATE_90_COUNTERCLOCKWISE)
resized_image4_rotated_90degreeleft = cv2.rotate(image4_resized, cv2.ROTATE_90_COUNTERCLOCKWISE)



In [115]:
# Here i rotated  cat's  and dog's images to right by 90 degree.

rotated_90degreeright_resized_image1 = cv2.rotate(image1_resized, cv2.ROTATE_90_CLOCKWISE)
rotated_90degreeright_resized_image2 = cv2.rotate(image2_resized, cv2.ROTATE_90_CLOCKWISE)
rotated_90degreeright_resized_image3 = cv2.rotate(image3_resized, cv2.ROTATE_90_CLOCKWISE)
rotated_90degreeright_resized_image4 = cv2.rotate(image4_resized, cv2.ROTATE_90_CLOCKWISE)

In [116]:
# Here i resized cat and dog images to half by keeping aspect ratio( Burada en boy oranını koruyarak kedi ve köpek görsellerini yarıya kadar yeniden boyutlandırdım())

half_resized_image1 = cv2.resize(image1_resized, (int(224/2), int(224/2)))
half_resized_image2 = cv2.resize(image2_resized, (int(224/2), int(224/2)))
half_resized_image3 = cv2.resize(image3_resized, (int(224/2), int(224/2)))
half_resized_image4 = cv2.resize(image4_resized, (int(224/2), int(224/2)))

In [117]:
# Displaying input and ouput of the images finally.


In [ ]:
# Demonstrating Cat1
# Creating figure


fig = plt.figure(figsize=(20, 20))

#setting values to rows and column variables
rows = 1
columns = 5

#Add subplots at their positions and show
fig.add_subplot(rows, columns, 1)
plt.imshow(resized_image1_vertically)
plt.title("vertically_resized_cat1")

fig.add_subplot(rows, columns, 2)
plt.imshow(resized_image1_horizontally)
plt.title("horizontally_resized_cat1")

fig.add_subplot(rows, columns, 3)
plt.imshow(resized_image1_rotated_90degreeleft)
plt.title("rotated_90degreeleft_resized_cat1")

fig.add_subplot(rows, columns, 4)
plt.imshow(rotated_90degreeright_resized_image1)
plt.title("rotated_90degreeright_resized_cat1")

fig.add_subplot(rows, columns, 5)
plt.imshow(half_resized_image1)
plt.title("half_resized_cat1")
plt.show()

# Demonstrating cat2
#create figure#

fig = plt.figure(figsize=(20, 20))

#setting values to rows and column variables
rows = 1
columns = 5

#Add subplots at their positions and show
fig.add_subplot(rows, columns, 1)
plt.imshow(resized_image2_vertically)
plt.title("vertically_resized_cat2")

fig.add_subplot(rows, columns, 2)
plt.imshow(resized_image2_horizontally)
plt.title("horizontally_resized_cat2")

fig.add_subplot(rows, columns, 3)
plt.imshow(resized_image2_rotated_90degreeleft)
plt.title("rotated_90degreeleft_resized_cat2")

fig.add_subplot(rows, columns, 4)
plt.imshow(rotated_90degreeright_resized_image2)
plt.title("rotated_90degreeright_resized_cat2")

fig.add_subplot(rows, columns, 5)
plt.imshow(half_resized_image2)
plt.title("half_resized_cat2")
plt.show()

#Demonstrating  cat3
#create figure
fig = plt.figure(figsize=(20, 20))

#setting values to rows and column variables
rows = 1
columns = 5

#Add subplots at their positions and show
fig.add_subplot(rows, columns, 1)
plt.imshow(resized_image3_vertically)
plt.title("vertically_resized_cat3")

fig.add_subplot(rows, columns, 2)
plt.imshow(resized_image3_horizontally)
plt.title("horizontally_resized_cat3")

fig.add_subplot(rows, columns, 3)
plt.imshow(resized_image3_rotated_90degreeleft)
plt.title("rotated_90degreeleft_resized_cat3")

fig.add_subplot(rows, columns, 4)
plt.imshow(rotated_90degreeright_resized_image3)
plt.title("rotated_90degreeright_resized_cat3")

fig.add_subplot(rows, columns, 5)
plt.imshow(half_resized_image3)
plt.title("half_resized_cat3")
plt.show()

# Demonstrating dog1
#create figure
fig = plt.figure(figsize=(20, 20))

#setting values to rows and column variables
rows = 1
columns = 5

#Add subplots at their positions and show
fig.add_subplot(rows, columns, 1)
plt.imshow(resized_image4_vertically)
plt.title("vertically_resized_dog1")

fig.add_subplot(rows, columns, 2)
plt.imshow(resized_image4_horizontally)
plt.title("horizontally_resized_dog1")

fig.add_subplot(rows, columns, 3)
plt.imshow(resized_image4_rotated_90degreeleft)
plt.title("resized_image4_rotated_90degreelef")

fig.add_subplot(rows, columns, 4)
plt.imshow(rotated_90degreeright_resized_image4)
plt.title("rotated_90degreeright_resized_dog1")

fig.add_subplot(rows, columns, 5)
plt.imshow(half_resized_image4)
plt.title("half_resized_dog1")
plt.show()
